#include <gtest/gtest.h>

#include "propagate/GpDataLoader.h"
#include "propagate/SatelliteTracker.h"

namespace {

// A real ISS element set (frozen, not "now") so these tests are fully
// reproducible. Expected values below were generated by this same
// Propagate code against this same orbit, so this is a regression/plumbing
// test -- it confirms the CSV/JSON/KVN/XML/TLE parsers all feed the SGP4
// engine identically and that the wiring (dlopen, license lookup, rpath)
// actually works end to end -- not an independent check of SGP4 itself,
// which is the vendor's own reference implementation.
//
// Each format below is given a *different* NORAD catalog number (all other
// orbital elements identical) purely so the five satellites don't collide
// as "already loaded" duplicates when every test runs in the same process
// -- the catalog number doesn't feed into the SGP4 math, so the expected
// position/velocity below is identical for all of them.
const char* kIssTle =
    "1 25544U 98067A   26225.85824407  .00004307  00000+0  85020-4 0  9997\n"
    "2 25544  51.6326  14.6698 0007494  43.6909 316.4672 15.49433609580695\n";

const char* kIssCsv =
    "OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,"
    "ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,"
    "ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT\n"
    "ISS (ZARYA),1998-067A,2026-08-13T20:35:52.287648,15.49433609,.00074948,51.6326,"
    "14.6698,43.6909,316.4672,0,U,25545,999,58069,.85019655E-4,.4307E-4,0\n";

const char* kIssJson =
    "[{\"OBJECT_NAME\":\"ISS (ZARYA)\",\"OBJECT_ID\":\"1998-067A\","
    "\"EPOCH\":\"2026-08-13T20:35:52.287648\",\"MEAN_MOTION\":15.49433609,"
    "\"ECCENTRICITY\":0.00074948,\"INCLINATION\":51.6326,\"RA_OF_ASC_NODE\":14.6698,"
    "\"ARG_OF_PERICENTER\":43.6909,\"MEAN_ANOMALY\":316.4672,\"EPHEMERIS_TYPE\":0,"
    "\"CLASSIFICATION_TYPE\":\"U\",\"NORAD_CAT_ID\":25546,\"ELEMENT_SET_NO\":999,"
    "\"REV_AT_EPOCH\":58069,\"BSTAR\":8.5019655e-5,\"MEAN_MOTION_DOT\":4.307e-5,"
    "\"MEAN_MOTION_DDOT\":0}]";

const char* kIssKvn =
    "CCSDS_OMM_VERS = 2.0\n"
    "CREATION_DATE  = \n"
    "ORIGINATOR     = \n"
    "\n"
    "OBJECT_NAME    = ISS (ZARYA)\n"
    "OBJECT_ID      = 1998-067A\n"
    "CENTER_NAME    = EARTH\n"
    "REF_FRAME      = TEME\n"
    "TIME_SYSTEM    = UTC\n"
    "MEAN_ELEMENT_THEORY = SGP/SGP4\n"
    "\n"
    "EPOCH          = 2026-08-13T20:35:52.287648\n"
    "MEAN_MOTION    = 15.49433609\n"
    "ECCENTRICITY   = .00074948\n"
    "INCLINATION    = 51.6326\n"
    "RA_OF_ASC_NODE = 14.6698\n"
    "ARG_OF_PERICENTER = 43.6909\n"
    "MEAN_ANOMALY   = 316.4672\n"
    "\n"
    "EPHEMERIS_TYPE = 0\n"
    "CLASSIFICATION_TYPE = U\n"
    "NORAD_CAT_ID   = 25547\n"
    "ELEMENT_SET_NO = 999\n"
    "REV_AT_EPOCH   = 58069\n"
    "BSTAR          = .85019655E-4\n"
    "MEAN_MOTION_DOT = .4307E-4\n"
    "MEAN_MOTION_DDOT = 0\n";

const char* kIssXml =
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<ndm><omm id=\"CCSDS_OMM_VERS\" version=\"2.0\">\n"
    "<header><CREATION_DATE/><ORIGINATOR/></header><body><segment><metadata>"
    "<OBJECT_NAME>ISS (ZARYA)</OBJECT_NAME><OBJECT_ID>1998-067A</OBJECT_ID>"
    "<CENTER_NAME>EARTH</CENTER_NAME><REF_FRAME>TEME</REF_FRAME><TIME_SYSTEM>UTC</TIME_SYSTEM>"
    "<MEAN_ELEMENT_THEORY>SGP4</MEAN_ELEMENT_THEORY></metadata><data><meanElements>"
    "<EPOCH>2026-08-13T20:35:52.287648</EPOCH><MEAN_MOTION>15.49433609</MEAN_MOTION>"
    "<ECCENTRICITY>.00074948</ECCENTRICITY><INCLINATION>51.6326</INCLINATION>"
    "<RA_OF_ASC_NODE>14.6698</RA_OF_ASC_NODE><ARG_OF_PERICENTER>43.6909</ARG_OF_PERICENTER>"
    "<MEAN_ANOMALY>316.4672</MEAN_ANOMALY></meanElements><tleParameters>"
    "<EPHEMERIS_TYPE>0</EPHEMERIS_TYPE><CLASSIFICATION_TYPE>U</CLASSIFICATION_TYPE>"
    "<NORAD_CAT_ID>25548</NORAD_CAT_ID><ELEMENT_SET_NO>999</ELEMENT_SET_NO>"
    "<REV_AT_EPOCH>58069</REV_AT_EPOCH><BSTAR>.85019655E-4</BSTAR>"
    "<MEAN_MOTION_DOT>.4307E-4</MEAN_MOTION_DOT><MEAN_MOTION_DDOT>0</MEAN_MOTION_DDOT>"
    "</tleParameters></data></segment></body></omm></ndm>\n";

// Same orbit again under yet another catalog number, for the auto-detect
// and PropagateToNow tests (which also run in this same process).
const char* kIssJsonAutoDetect =
    "[{\"OBJECT_NAME\":\"ISS (ZARYA)\",\"OBJECT_ID\":\"1998-067A\","
    "\"EPOCH\":\"2026-08-13T20:35:52.287648\",\"MEAN_MOTION\":15.49433609,"
    "\"ECCENTRICITY\":0.00074948,\"INCLINATION\":51.6326,\"RA_OF_ASC_NODE\":14.6698,"
    "\"ARG_OF_PERICENTER\":43.6909,\"MEAN_ANOMALY\":316.4672,\"EPHEMERIS_TYPE\":0,"
    "\"CLASSIFICATION_TYPE\":\"U\",\"NORAD_CAT_ID\":25549,\"ELEMENT_SET_NO\":999,"
    "\"REV_AT_EPOCH\":58069,\"BSTAR\":8.5019655e-5,\"MEAN_MOTION_DOT\":4.307e-5,"
    "\"MEAN_MOTION_DDOT\":0}]";

const char* kIssTleForNowTest =
    "1 25550U 98067A   26225.85824407  .00004307  00000+0  85020-4 0  9997\n"
    "2 25550  51.6326  14.6698 0007494  43.6909 316.4672 15.49433609580695\n";

// Reference values: this exact TLE, propagated to 2026-08-15 12:00:00 UTC,
// via this exact code path (see the comment above kIssTle).
constexpr double kExpectedPosKm[3] = {-6626.15854942127, 405.947579476471, 1461.45196399303};
constexpr double kExpectedVelKmS[3] = {-1.57947036474516, -4.77905480723652, -5.7744093524804};
constexpr double kExpectedLatDeg = 12.4913621043409;
constexpr double kExpectedLonDeg = 32.5842023592089;
constexpr double kExpectedAltKm = 420.402423603849;

// The TLE-format test matches these bit-for-bit (it feeds Sgp4Prop the
// exact same epoch fraction encoded in the TLE line). CSV/JSON/KVN/XML
// instead go through TimeComps2ToUTC()/UTCToYrDays() to turn an ISO
// timestamp into (year, day-of-year), which loses a few microseconds of
// epoch precision in the round trip -- observed ~1e-3 km / ~1e-6 deg on
// macOS. These tolerances are set generously above that (~15x) to absorb
// both that expected rounding and ordinary cross-platform/compiler libm
// differences, while still catching a real regression (wrong field,
// wrong units, wrong epoch conversion, etc).
constexpr double kPosTolKm = 1e-2;     // 10 m
constexpr double kVelTolKmS = 1e-5;    // 1 cm/s
constexpr double kAngleTolDeg = 1e-4;  // ~11 m at the equator

void ExpectMatchesReference(const Propagate::SatelliteState& s) {
    ASSERT_TRUE(s.ok);
    EXPECT_NEAR(s.positionKm[0], kExpectedPosKm[0], kPosTolKm);
    EXPECT_NEAR(s.positionKm[1], kExpectedPosKm[1], kPosTolKm);
    EXPECT_NEAR(s.positionKm[2], kExpectedPosKm[2], kPosTolKm);
    EXPECT_NEAR(s.velocityKmS[0], kExpectedVelKmS[0], kVelTolKmS);
    EXPECT_NEAR(s.velocityKmS[1], kExpectedVelKmS[1], kVelTolKmS);
    EXPECT_NEAR(s.velocityKmS[2], kExpectedVelKmS[2], kVelTolKmS);
    EXPECT_NEAR(s.latitudeDeg, kExpectedLatDeg, kAngleTolDeg);
    EXPECT_NEAR(s.longitudeDeg, kExpectedLonDeg, kAngleTolDeg);
    EXPECT_NEAR(s.heightKm, kExpectedAltKm, kPosTolKm);
}

} // namespace

TEST(GpDataLoader, DetectsEachFormat) {
    EXPECT_EQ(Propagate::DetectFormat(kIssTle), Propagate::GpFormat::Tle);
    EXPECT_EQ(Propagate::DetectFormat(kIssCsv), Propagate::GpFormat::Csv);
    EXPECT_EQ(Propagate::DetectFormat(kIssJson), Propagate::GpFormat::Json);
    EXPECT_EQ(Propagate::DetectFormat(kIssKvn), Propagate::GpFormat::OmmKvn);
    EXPECT_EQ(Propagate::DetectFormat(kIssXml), Propagate::GpFormat::OmmXml);
}

TEST(GpDataLoader, RejectsGarbageInput) {
    auto keys = Propagate::LoadGpData("this is not any known GP format\n");
    EXPECT_TRUE(keys.empty());
}

TEST(GpDataLoader, RejectsEmptyInput) {
    auto keys = Propagate::LoadGpData("");
    EXPECT_TRUE(keys.empty());
}

// One correctness test per format: load a single satellite with that
// format's parser, propagate to the same fixed UTC time, and check the
// result against the shared reference values above -- proves every parser
// feeds SGP4 the same orbit, not just that each one "loads without error".

TEST(Propagate, TleFormatMatchesReference) {
    auto keys = Propagate::LoadGpData(kIssTle, Propagate::GpFormat::Tle);
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, CsvFormatMatchesReference) {
    auto keys = Propagate::LoadGpData(kIssCsv, Propagate::GpFormat::Csv);
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, JsonFormatMatchesReference) {
    auto keys = Propagate::LoadGpData(kIssJson, Propagate::GpFormat::Json);
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, OmmKvnFormatMatchesReference) {
    auto keys = Propagate::LoadGpData(kIssKvn, Propagate::GpFormat::OmmKvn);
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, OmmXmlFormatMatchesReference) {
    auto keys = Propagate::LoadGpData(kIssXml, Propagate::GpFormat::OmmXml);
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, AutoDetectFindsSameAnswerAsExplicitFormat) {
    auto keys = Propagate::LoadGpData(kIssJsonAutoDetect); // GpFormat::Auto by default
    ASSERT_EQ(keys.size(), 1u);
    ExpectMatchesReference(Propagate::PropagateToUtc(keys[0], 2026, 8, 15, 12, 0, 0.0));
}

TEST(Propagate, PropagateToNowReturnsOkForRecentElementSet) {
    // Can't assert a specific position for "now" (it depends on when the
    // test runs), but a real, recent element set should propagate cleanly.
    auto keys = Propagate::LoadGpData(kIssTleForNowTest, Propagate::GpFormat::Tle);
    ASSERT_EQ(keys.size(), 1u);
    auto state = Propagate::PropagateToNow(keys[0]);
    EXPECT_TRUE(state.ok);
    // Sanity range, not a precise check: low Earth orbit altitude.
    EXPECT_GT(state.heightKm, 300.0);
    EXPECT_LT(state.heightKm, 500.0);
}
